# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: modules/perception/pipeline/proto/stage/all_latest_fusion_config.proto
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='modules/perception/pipeline/proto/stage/all_latest_fusion_config.proto',
  package='apollo.perception.fusion',
  syntax='proto2',
  serialized_options=None,
  create_key=_descriptor._internal_create_key,
  serialized_pb=b'\nFmodules/perception/pipeline/proto/stage/all_latest_fusion_config.proto\x12\x18\x61pollo.perception.fusion\"x\n\x15\x41llLatestFusionConfig\x12\x13\n\x0bmain_sensor\x18\x01 \x01(\t\x12\x17\n\tuse_lidar\x18\x02 \x01(\x08:\x04true\x12\x17\n\tuse_radar\x18\x03 \x01(\x08:\x04true\x12\x18\n\nuse_camera\x18\x04 \x01(\x08:\x04true'
)




_ALLLATESTFUSIONCONFIG = _descriptor.Descriptor(
  name='AllLatestFusionConfig',
  full_name='apollo.perception.fusion.AllLatestFusionConfig',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='main_sensor', full_name='apollo.perception.fusion.AllLatestFusionConfig.main_sensor', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='use_lidar', full_name='apollo.perception.fusion.AllLatestFusionConfig.use_lidar', index=1,
      number=2, type=8, cpp_type=7, label=1,
      has_default_value=True, default_value=True,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='use_radar', full_name='apollo.perception.fusion.AllLatestFusionConfig.use_radar', index=2,
      number=3, type=8, cpp_type=7, label=1,
      has_default_value=True, default_value=True,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='use_camera', full_name='apollo.perception.fusion.AllLatestFusionConfig.use_camera', index=3,
      number=4, type=8, cpp_type=7, label=1,
      has_default_value=True, default_value=True,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto2',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=100,
  serialized_end=220,
)

DESCRIPTOR.message_types_by_name['AllLatestFusionConfig'] = _ALLLATESTFUSIONCONFIG
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

AllLatestFusionConfig = _reflection.GeneratedProtocolMessageType('AllLatestFusionConfig', (_message.Message,), {
  'DESCRIPTOR' : _ALLLATESTFUSIONCONFIG,
  '__module__' : 'modules.perception.pipeline.proto.stage.all_latest_fusion_config_pb2'
  # @@protoc_insertion_point(class_scope:apollo.perception.fusion.AllLatestFusionConfig)
  })
_sym_db.RegisterMessage(AllLatestFusionConfig)


# @@protoc_insertion_point(module_scope)
