# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: modules/perception/pipeline/proto/stage/cnnseg_config.proto
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='modules/perception/pipeline/proto/stage/cnnseg_config.proto',
  package='apollo.perception.lidar',
  syntax='proto2',
  serialized_options=None,
  create_key=_descriptor._internal_create_key,
  serialized_pb=b'\n;modules/perception/pipeline/proto/stage/cnnseg_config.proto\x12\x17\x61pollo.perception.lidar\"\x86\x02\n\x0c\x43NNSegConfig\x12\x33\n\nparam_file\x18\x01 \x01(\t:\x1f./data/models/cnnseg/param.conf\x12\x38\n\nproto_file\x18\x02 \x01(\t:$./data/models/cnnseg/deploy.prototxt\x12;\n\x0bweight_file\x18\x03 \x01(\t:&./data/models/cnnseg/deploy.caffemodel\x12\x35\n\x0b\x65ngine_file\x18\x04 \x01(\t: ./data/models/cnnseg/engine.conf\x12\x13\n\x0bsensor_name\x18\x05 \x01(\t'
)




_CNNSEGCONFIG = _descriptor.Descriptor(
  name='CNNSegConfig',
  full_name='apollo.perception.lidar.CNNSegConfig',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='param_file', full_name='apollo.perception.lidar.CNNSegConfig.param_file', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=True, default_value=b"./data/models/cnnseg/param.conf".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='proto_file', full_name='apollo.perception.lidar.CNNSegConfig.proto_file', index=1,
      number=2, type=9, cpp_type=9, label=1,
      has_default_value=True, default_value=b"./data/models/cnnseg/deploy.prototxt".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='weight_file', full_name='apollo.perception.lidar.CNNSegConfig.weight_file', index=2,
      number=3, type=9, cpp_type=9, label=1,
      has_default_value=True, default_value=b"./data/models/cnnseg/deploy.caffemodel".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='engine_file', full_name='apollo.perception.lidar.CNNSegConfig.engine_file', index=3,
      number=4, type=9, cpp_type=9, label=1,
      has_default_value=True, default_value=b"./data/models/cnnseg/engine.conf".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='sensor_name', full_name='apollo.perception.lidar.CNNSegConfig.sensor_name', index=4,
      number=5, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto2',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=89,
  serialized_end=351,
)

DESCRIPTOR.message_types_by_name['CNNSegConfig'] = _CNNSEGCONFIG
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

CNNSegConfig = _reflection.GeneratedProtocolMessageType('CNNSegConfig', (_message.Message,), {
  'DESCRIPTOR' : _CNNSEGCONFIG,
  '__module__' : 'modules.perception.pipeline.proto.stage.cnnseg_config_pb2'
  # @@protoc_insertion_point(class_scope:apollo.perception.lidar.CNNSegConfig)
  })
_sym_db.RegisterMessage(CNNSegConfig)


# @@protoc_insertion_point(module_scope)
