# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: modules/perception/pipeline/proto/stage/darkSCNN.proto
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='modules/perception/pipeline/proto/stage/darkSCNN.proto',
  package='apollo.perception.camera.darkSCNN',
  syntax='proto2',
  serialized_options=None,
  create_key=_descriptor._internal_create_key,
  serialized_pb=b'\n6modules/perception/pipeline/proto/stage/darkSCNN.proto\x12!apollo.perception.camera.darkSCNN\"\xce\x01\n\rDarkSCNNParam\x12\x42\n\x0bmodel_param\x18\x01 \x01(\x0b\x32-.apollo.perception.camera.darkSCNN.ModelParam\x12\x42\n\tnet_param\x18\x02 \x01(\x0b\x32/.apollo.perception.camera.darkSCNN.NetworkParam\x12\x10\n\x08root_dir\x18\x03 \x01(\t\x12\x0e\n\x06gpu_id\x18\x04 \x01(\x05\x12\x13\n\x0b\x63\x61mera_name\x18\x05 \x01(\t\"\x9b\x04\n\nModelParam\x12\x1c\n\nmodel_name\x18\x01 \x01(\t:\x08\x64\x61rkSCNN\x12#\n\nproto_file\x18\x02 \x01(\t:\x0f\x64\x65ploy.prototxt\x12&\n\x0bweight_file\x18\x03 \x01(\t:\x11\x64\x65ploy.caffemodel\x12\x19\n\x0einput_offset_y\x18\x04 \x01(\r:\x01\x30\x12\x19\n\x0einput_offset_x\x18\x05 \x01(\r:\x01\x30\x12\x19\n\x0b\x63rop_height\x18\x06 \x01(\r:\x04\x31\x30\x38\x30\x12\x18\n\ncrop_width\x18\x07 \x01(\r:\x04\x31\x39\x32\x30\x12\x1a\n\rresize_height\x18\x08 \x01(\r:\x03\x35\x31\x32\x12\x19\n\x0cresize_width\x18\t \x01(\r:\x03\x35\x31\x32\x12\x12\n\x06mean_b\x18\n \x01(\r:\x02\x39\x35\x12\x12\n\x06mean_g\x18\x0b \x01(\r:\x02\x39\x39\x12\x12\n\x06mean_r\x18\x0c \x01(\r:\x02\x39\x36\x12\x14\n\x06is_bgr\x18\r \x01(\x08:\x04true\x12!\n\x14\x63onfidence_threshold\x18\x0e \x01(\x02:\x03\x30.5\x12\x16\n\x0bvpt_mean_dx\x18\x0f \x01(\x02:\x01\x30\x12\x1c\n\x0bvpt_mean_dy\x18\x10 \x01(\x02:\x07-77.284\x12\x1b\n\nvpt_std_dx\x18\x11 \x01(\x02:\x07\x31\x30\x33.109\x12\x1a\n\nvpt_std_dy\x18\x12 \x01(\x02:\x06\x39\x35.273\x12\x1c\n\nmodel_type\x18\x13 \x01(\t:\x08\x43\x61\x66\x66\x65Net\"]\n\x0cNetworkParam\x12\x19\n\x08seg_blob\x18\x01 \x01(\t:\x07softmax\x12\x18\n\x08vpt_blob\x18\x02 \x01(\t:\x06\x66\x63_out\x12\x18\n\ninput_blob\x18\x03 \x01(\t:\x04\x64\x61ta'
)




_DARKSCNNPARAM = _descriptor.Descriptor(
  name='DarkSCNNParam',
  full_name='apollo.perception.camera.darkSCNN.DarkSCNNParam',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='model_param', full_name='apollo.perception.camera.darkSCNN.DarkSCNNParam.model_param', index=0,
      number=1, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='net_param', full_name='apollo.perception.camera.darkSCNN.DarkSCNNParam.net_param', index=1,
      number=2, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='root_dir', full_name='apollo.perception.camera.darkSCNN.DarkSCNNParam.root_dir', index=2,
      number=3, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='gpu_id', full_name='apollo.perception.camera.darkSCNN.DarkSCNNParam.gpu_id', index=3,
      number=4, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='camera_name', full_name='apollo.perception.camera.darkSCNN.DarkSCNNParam.camera_name', index=4,
      number=5, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto2',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=94,
  serialized_end=300,
)


_MODELPARAM = _descriptor.Descriptor(
  name='ModelParam',
  full_name='apollo.perception.camera.darkSCNN.ModelParam',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='model_name', full_name='apollo.perception.camera.darkSCNN.ModelParam.model_name', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=True, default_value=b"darkSCNN".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='proto_file', full_name='apollo.perception.camera.darkSCNN.ModelParam.proto_file', index=1,
      number=2, type=9, cpp_type=9, label=1,
      has_default_value=True, default_value=b"deploy.prototxt".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='weight_file', full_name='apollo.perception.camera.darkSCNN.ModelParam.weight_file', index=2,
      number=3, type=9, cpp_type=9, label=1,
      has_default_value=True, default_value=b"deploy.caffemodel".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='input_offset_y', full_name='apollo.perception.camera.darkSCNN.ModelParam.input_offset_y', index=3,
      number=4, type=13, cpp_type=3, label=1,
      has_default_value=True, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='input_offset_x', full_name='apollo.perception.camera.darkSCNN.ModelParam.input_offset_x', index=4,
      number=5, type=13, cpp_type=3, label=1,
      has_default_value=True, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='crop_height', full_name='apollo.perception.camera.darkSCNN.ModelParam.crop_height', index=5,
      number=6, type=13, cpp_type=3, label=1,
      has_default_value=True, default_value=1080,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='crop_width', full_name='apollo.perception.camera.darkSCNN.ModelParam.crop_width', index=6,
      number=7, type=13, cpp_type=3, label=1,
      has_default_value=True, default_value=1920,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='resize_height', full_name='apollo.perception.camera.darkSCNN.ModelParam.resize_height', index=7,
      number=8, type=13, cpp_type=3, label=1,
      has_default_value=True, default_value=512,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='resize_width', full_name='apollo.perception.camera.darkSCNN.ModelParam.resize_width', index=8,
      number=9, type=13, cpp_type=3, label=1,
      has_default_value=True, default_value=512,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='mean_b', full_name='apollo.perception.camera.darkSCNN.ModelParam.mean_b', index=9,
      number=10, type=13, cpp_type=3, label=1,
      has_default_value=True, default_value=95,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='mean_g', full_name='apollo.perception.camera.darkSCNN.ModelParam.mean_g', index=10,
      number=11, type=13, cpp_type=3, label=1,
      has_default_value=True, default_value=99,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='mean_r', full_name='apollo.perception.camera.darkSCNN.ModelParam.mean_r', index=11,
      number=12, type=13, cpp_type=3, label=1,
      has_default_value=True, default_value=96,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='is_bgr', full_name='apollo.perception.camera.darkSCNN.ModelParam.is_bgr', index=12,
      number=13, type=8, cpp_type=7, label=1,
      has_default_value=True, default_value=True,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='confidence_threshold', full_name='apollo.perception.camera.darkSCNN.ModelParam.confidence_threshold', index=13,
      number=14, type=2, cpp_type=6, label=1,
      has_default_value=True, default_value=float(0.5),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='vpt_mean_dx', full_name='apollo.perception.camera.darkSCNN.ModelParam.vpt_mean_dx', index=14,
      number=15, type=2, cpp_type=6, label=1,
      has_default_value=True, default_value=float(0),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='vpt_mean_dy', full_name='apollo.perception.camera.darkSCNN.ModelParam.vpt_mean_dy', index=15,
      number=16, type=2, cpp_type=6, label=1,
      has_default_value=True, default_value=float(-77.284),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='vpt_std_dx', full_name='apollo.perception.camera.darkSCNN.ModelParam.vpt_std_dx', index=16,
      number=17, type=2, cpp_type=6, label=1,
      has_default_value=True, default_value=float(103.109),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='vpt_std_dy', full_name='apollo.perception.camera.darkSCNN.ModelParam.vpt_std_dy', index=17,
      number=18, type=2, cpp_type=6, label=1,
      has_default_value=True, default_value=float(95.273),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='model_type', full_name='apollo.perception.camera.darkSCNN.ModelParam.model_type', index=18,
      number=19, type=9, cpp_type=9, label=1,
      has_default_value=True, default_value=b"CaffeNet".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto2',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=303,
  serialized_end=842,
)


_NETWORKPARAM = _descriptor.Descriptor(
  name='NetworkParam',
  full_name='apollo.perception.camera.darkSCNN.NetworkParam',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='seg_blob', full_name='apollo.perception.camera.darkSCNN.NetworkParam.seg_blob', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=True, default_value=b"softmax".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='vpt_blob', full_name='apollo.perception.camera.darkSCNN.NetworkParam.vpt_blob', index=1,
      number=2, type=9, cpp_type=9, label=1,
      has_default_value=True, default_value=b"fc_out".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='input_blob', full_name='apollo.perception.camera.darkSCNN.NetworkParam.input_blob', index=2,
      number=3, type=9, cpp_type=9, label=1,
      has_default_value=True, default_value=b"data".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto2',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=844,
  serialized_end=937,
)

_DARKSCNNPARAM.fields_by_name['model_param'].message_type = _MODELPARAM
_DARKSCNNPARAM.fields_by_name['net_param'].message_type = _NETWORKPARAM
DESCRIPTOR.message_types_by_name['DarkSCNNParam'] = _DARKSCNNPARAM
DESCRIPTOR.message_types_by_name['ModelParam'] = _MODELPARAM
DESCRIPTOR.message_types_by_name['NetworkParam'] = _NETWORKPARAM
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

DarkSCNNParam = _reflection.GeneratedProtocolMessageType('DarkSCNNParam', (_message.Message,), {
  'DESCRIPTOR' : _DARKSCNNPARAM,
  '__module__' : 'modules.perception.pipeline.proto.stage.darkSCNN_pb2'
  # @@protoc_insertion_point(class_scope:apollo.perception.camera.darkSCNN.DarkSCNNParam)
  })
_sym_db.RegisterMessage(DarkSCNNParam)

ModelParam = _reflection.GeneratedProtocolMessageType('ModelParam', (_message.Message,), {
  'DESCRIPTOR' : _MODELPARAM,
  '__module__' : 'modules.perception.pipeline.proto.stage.darkSCNN_pb2'
  # @@protoc_insertion_point(class_scope:apollo.perception.camera.darkSCNN.ModelParam)
  })
_sym_db.RegisterMessage(ModelParam)

NetworkParam = _reflection.GeneratedProtocolMessageType('NetworkParam', (_message.Message,), {
  'DESCRIPTOR' : _NETWORKPARAM,
  '__module__' : 'modules.perception.pipeline.proto.stage.darkSCNN_pb2'
  # @@protoc_insertion_point(class_scope:apollo.perception.camera.darkSCNN.NetworkParam)
  })
_sym_db.RegisterMessage(NetworkParam)


# @@protoc_insertion_point(module_scope)
