# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: modules/perception/pipeline/proto/stage/denseline_postprocessor.proto
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='modules/perception/pipeline/proto/stage/denseline_postprocessor.proto',
  package='apollo.perception.camera.lane',
  syntax='proto2',
  serialized_options=None,
  create_key=_descriptor._internal_create_key,
  serialized_pb=b'\nEmodules/perception/pipeline/proto/stage/denseline_postprocessor.proto\x12\x1d\x61pollo.perception.camera.lane\"\xe9\x02\n\x16LanePostprocessorParam\x12\x1f\n\x14omit_bottom_line_num\x18\x01 \x01(\x05:\x01\x33\x12&\n\x19laneline_map_score_thresh\x18\x02 \x01(\x02:\x03\x30.4\x12(\n\x1blaneline_point_score_thresh\x18\x03 \x01(\x02:\x03\x30.6\x12(\n\x1dlaneline_point_min_num_thresh\x18\x04 \x01(\x05:\x01\x32\x12 \n\x15\x63\x63_valid_pixels_ratio\x18\x05 \x01(\x02:\x01\x32\x12\'\n\x1blaneline_reject_dist_thresh\x18\x06 \x01(\x02:\x02\x35\x30\x12\x19\n\x0einput_offset_x\x18\x07 \x01(\r:\x01\x30\x12\x19\n\x0einput_offset_y\x18\x08 \x01(\r:\x01\x30\x12\x18\n\x0b\x63rop_height\x18\t \x01(\r:\x03\x35\x31\x32\x12\x17\n\ncrop_width\x18\n \x01(\r:\x03\x35\x31\x32'
)




_LANEPOSTPROCESSORPARAM = _descriptor.Descriptor(
  name='LanePostprocessorParam',
  full_name='apollo.perception.camera.lane.LanePostprocessorParam',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='omit_bottom_line_num', full_name='apollo.perception.camera.lane.LanePostprocessorParam.omit_bottom_line_num', index=0,
      number=1, type=5, cpp_type=1, label=1,
      has_default_value=True, default_value=3,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='laneline_map_score_thresh', full_name='apollo.perception.camera.lane.LanePostprocessorParam.laneline_map_score_thresh', index=1,
      number=2, type=2, cpp_type=6, label=1,
      has_default_value=True, default_value=float(0.4),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='laneline_point_score_thresh', full_name='apollo.perception.camera.lane.LanePostprocessorParam.laneline_point_score_thresh', index=2,
      number=3, type=2, cpp_type=6, label=1,
      has_default_value=True, default_value=float(0.6),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='laneline_point_min_num_thresh', full_name='apollo.perception.camera.lane.LanePostprocessorParam.laneline_point_min_num_thresh', index=3,
      number=4, type=5, cpp_type=1, label=1,
      has_default_value=True, default_value=2,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='cc_valid_pixels_ratio', full_name='apollo.perception.camera.lane.LanePostprocessorParam.cc_valid_pixels_ratio', index=4,
      number=5, type=2, cpp_type=6, label=1,
      has_default_value=True, default_value=float(2),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='laneline_reject_dist_thresh', full_name='apollo.perception.camera.lane.LanePostprocessorParam.laneline_reject_dist_thresh', index=5,
      number=6, type=2, cpp_type=6, label=1,
      has_default_value=True, default_value=float(50),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='input_offset_x', full_name='apollo.perception.camera.lane.LanePostprocessorParam.input_offset_x', index=6,
      number=7, type=13, cpp_type=3, label=1,
      has_default_value=True, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='input_offset_y', full_name='apollo.perception.camera.lane.LanePostprocessorParam.input_offset_y', index=7,
      number=8, type=13, cpp_type=3, label=1,
      has_default_value=True, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='crop_height', full_name='apollo.perception.camera.lane.LanePostprocessorParam.crop_height', index=8,
      number=9, type=13, cpp_type=3, label=1,
      has_default_value=True, default_value=512,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='crop_width', full_name='apollo.perception.camera.lane.LanePostprocessorParam.crop_width', index=9,
      number=10, type=13, cpp_type=3, label=1,
      has_default_value=True, default_value=512,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto2',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=105,
  serialized_end=466,
)

DESCRIPTOR.message_types_by_name['LanePostprocessorParam'] = _LANEPOSTPROCESSORPARAM
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

LanePostprocessorParam = _reflection.GeneratedProtocolMessageType('LanePostprocessorParam', (_message.Message,), {
  'DESCRIPTOR' : _LANEPOSTPROCESSORPARAM,
  '__module__' : 'modules.perception.pipeline.proto.stage.denseline_postprocessor_pb2'
  # @@protoc_insertion_point(class_scope:apollo.perception.camera.lane.LanePostprocessorParam)
  })
_sym_db.RegisterMessage(LanePostprocessorParam)


# @@protoc_insertion_point(module_scope)
