# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: modules/perception/pipeline/proto/stage/location_refiner.proto
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='modules/perception/pipeline/proto/stage/location_refiner.proto',
  package='apollo.perception.camera.location_refiner',
  syntax='proto2',
  serialized_options=None,
  create_key=_descriptor._internal_create_key,
  serialized_pb=b'\n>modules/perception/pipeline/proto/stage/location_refiner.proto\x12)apollo.perception.camera.location_refiner\"W\n\x14LocationRefinerParam\x12\x1e\n\x12min_dist_to_camera\x18\x01 \x01(\x02:\x02\x33\x30\x12\x1f\n\x12roi_h2bottom_scale\x18\x02 \x01(\x02:\x03\x30.5'
)




_LOCATIONREFINERPARAM = _descriptor.Descriptor(
  name='LocationRefinerParam',
  full_name='apollo.perception.camera.location_refiner.LocationRefinerParam',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='min_dist_to_camera', full_name='apollo.perception.camera.location_refiner.LocationRefinerParam.min_dist_to_camera', index=0,
      number=1, type=2, cpp_type=6, label=1,
      has_default_value=True, default_value=float(30),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='roi_h2bottom_scale', full_name='apollo.perception.camera.location_refiner.LocationRefinerParam.roi_h2bottom_scale', index=1,
      number=2, type=2, cpp_type=6, label=1,
      has_default_value=True, default_value=float(0.5),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto2',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=109,
  serialized_end=196,
)

DESCRIPTOR.message_types_by_name['LocationRefinerParam'] = _LOCATIONREFINERPARAM
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

LocationRefinerParam = _reflection.GeneratedProtocolMessageType('LocationRefinerParam', (_message.Message,), {
  'DESCRIPTOR' : _LOCATIONREFINERPARAM,
  '__module__' : 'modules.perception.pipeline.proto.stage.location_refiner_pb2'
  # @@protoc_insertion_point(class_scope:apollo.perception.camera.location_refiner.LocationRefinerParam)
  })
_sym_db.RegisterMessage(LocationRefinerParam)


# @@protoc_insertion_point(module_scope)
