# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: modules/perception/pipeline/proto/stage/mlf_engine_config.proto
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='modules/perception/pipeline/proto/stage/mlf_engine_config.proto',
  package='apollo.perception.lidar',
  syntax='proto2',
  serialized_options=None,
  create_key=_descriptor._internal_create_key,
  serialized_pb=b'\n?modules/perception/pipeline/proto/stage/mlf_engine_config.proto\x12\x17\x61pollo.perception.lidar\"\xde\x01\n\x0fMlfEngineConfig\x12\x13\n\x0bmain_sensor\x18\x01 \x03(\t\x12%\n\x17use_histogram_for_match\x18\x02 \x01(\x08:\x04true\x12\x1e\n\x12histogram_bin_size\x18\x03 \x01(\r:\x02\x31\x30\x12%\n\x16output_predict_objects\x18\x04 \x01(\x08:\x05\x66\x61lse\x12$\n\x17reserved_invisible_time\x18\x05 \x01(\x01:\x03\x30.2\x12\"\n\x13use_frame_timestamp\x18\x06 \x01(\x08:\x05\x66\x61lse'
)




_MLFENGINECONFIG = _descriptor.Descriptor(
  name='MlfEngineConfig',
  full_name='apollo.perception.lidar.MlfEngineConfig',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='main_sensor', full_name='apollo.perception.lidar.MlfEngineConfig.main_sensor', index=0,
      number=1, type=9, cpp_type=9, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='use_histogram_for_match', full_name='apollo.perception.lidar.MlfEngineConfig.use_histogram_for_match', index=1,
      number=2, type=8, cpp_type=7, label=1,
      has_default_value=True, default_value=True,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='histogram_bin_size', full_name='apollo.perception.lidar.MlfEngineConfig.histogram_bin_size', index=2,
      number=3, type=13, cpp_type=3, label=1,
      has_default_value=True, default_value=10,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='output_predict_objects', full_name='apollo.perception.lidar.MlfEngineConfig.output_predict_objects', index=3,
      number=4, type=8, cpp_type=7, label=1,
      has_default_value=True, default_value=False,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='reserved_invisible_time', full_name='apollo.perception.lidar.MlfEngineConfig.reserved_invisible_time', index=4,
      number=5, type=1, cpp_type=5, label=1,
      has_default_value=True, default_value=float(0.2),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='use_frame_timestamp', full_name='apollo.perception.lidar.MlfEngineConfig.use_frame_timestamp', index=5,
      number=6, type=8, cpp_type=7, label=1,
      has_default_value=True, default_value=False,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto2',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=93,
  serialized_end=315,
)

DESCRIPTOR.message_types_by_name['MlfEngineConfig'] = _MLFENGINECONFIG
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

MlfEngineConfig = _reflection.GeneratedProtocolMessageType('MlfEngineConfig', (_message.Message,), {
  'DESCRIPTOR' : _MLFENGINECONFIG,
  '__module__' : 'modules.perception.pipeline.proto.stage.mlf_engine_config_pb2'
  # @@protoc_insertion_point(class_scope:apollo.perception.lidar.MlfEngineConfig)
  })
_sym_db.RegisterMessage(MlfEngineConfig)


# @@protoc_insertion_point(module_scope)
