# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: modules/perception/pipeline/proto/stage/multicue.proto
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='modules/perception/pipeline/proto/stage/multicue.proto',
  package='apollo.perception.camera.multicue',
  syntax='proto2',
  serialized_options=None,
  create_key=_descriptor._internal_create_key,
  serialized_pb=b'\n6modules/perception/pipeline/proto/stage/multicue.proto\x12!apollo.perception.camera.multicue\"N\n\rMulticueParam\x12\x1e\n\x11min_dimension_val\x18\x01 \x01(\x02:\x03\x30.2\x12\x1d\n\x0f\x63heck_dimension\x18\x02 \x01(\x08:\x04true'
)




_MULTICUEPARAM = _descriptor.Descriptor(
  name='MulticueParam',
  full_name='apollo.perception.camera.multicue.MulticueParam',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='min_dimension_val', full_name='apollo.perception.camera.multicue.MulticueParam.min_dimension_val', index=0,
      number=1, type=2, cpp_type=6, label=1,
      has_default_value=True, default_value=float(0.2),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='check_dimension', full_name='apollo.perception.camera.multicue.MulticueParam.check_dimension', index=1,
      number=2, type=8, cpp_type=7, label=1,
      has_default_value=True, default_value=True,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto2',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=93,
  serialized_end=171,
)

DESCRIPTOR.message_types_by_name['MulticueParam'] = _MULTICUEPARAM
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

MulticueParam = _reflection.GeneratedProtocolMessageType('MulticueParam', (_message.Message,), {
  'DESCRIPTOR' : _MULTICUEPARAM,
  '__module__' : 'modules.perception.pipeline.proto.stage.multicue_pb2'
  # @@protoc_insertion_point(class_scope:apollo.perception.camera.multicue.MulticueParam)
  })
_sym_db.RegisterMessage(MulticueParam)


# @@protoc_insertion_point(module_scope)
