# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: modules/perception/pipeline/proto/stage/recognition.proto
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='modules/perception/pipeline/proto/stage/recognition.proto',
  package='apollo.perception.camera',
  syntax='proto2',
  serialized_options=None,
  create_key=_descriptor._internal_create_key,
  serialized_pb=b'\n9modules/perception/pipeline/proto/stage/recognition.proto\x12\x18\x61pollo.perception.camera\"\xee\x03\n\rClassifyParam\x12\x12\n\nmodel_name\x18\x01 \x01(\t\x12\x1c\n\nmodel_type\x18\x02 \x01(\t:\x08\x43\x61\x66\x66\x65Net\x12\x12\n\ninput_blob\x18\x03 \x01(\t\x12\x13\n\x0boutput_blob\x18\x04 \x01(\t\x12\x13\n\x0bweight_file\x18\x05 \x01(\t\x12\x12\n\nproto_file\x18\x06 \x01(\t\x12\x1a\n\x12\x63lassify_threshold\x18\x07 \x01(\x02\x12\x1d\n\x15\x63lassify_resize_width\x18\x08 \x01(\x05\x12\x1e\n\x16\x63lassify_resize_height\x18\t \x01(\x05\x12\r\n\x05scale\x18\n \x01(\x02\x12\x12\n\x06mean_b\x18\x0c \x01(\x02:\x02\x39\x35\x12\x12\n\x06mean_g\x18\r \x01(\x02:\x02\x39\x39\x12\x12\n\x06mean_r\x18\x0e \x01(\x02:\x02\x39\x36\x12\x14\n\x06is_bgr\x18\x0f \x01(\x08:\x04true\x12\x89\x01\n\"traffic_light_recognition_root_dir\x18\x10 \x01(\t:]/apollo/modules/perception/production/data/perception/camera/models/traffic_light_recognition\x12\x11\n\x06gpu_id\x18\x11 \x01(\x05:\x01\x30\"\xe4\x01\n\x1dTrafficLightRecognitionConfig\x12?\n\x0evertical_model\x18\x01 \x01(\x0b\x32\'.apollo.perception.camera.ClassifyParam\x12?\n\x0equadrate_model\x18\x02 \x01(\x0b\x32\'.apollo.perception.camera.ClassifyParam\x12\x41\n\x10horizontal_model\x18\x03 \x01(\x0b\x32\'.apollo.perception.camera.ClassifyParam'
)




_CLASSIFYPARAM = _descriptor.Descriptor(
  name='ClassifyParam',
  full_name='apollo.perception.camera.ClassifyParam',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='model_name', full_name='apollo.perception.camera.ClassifyParam.model_name', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='model_type', full_name='apollo.perception.camera.ClassifyParam.model_type', index=1,
      number=2, type=9, cpp_type=9, label=1,
      has_default_value=True, default_value=b"CaffeNet".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='input_blob', full_name='apollo.perception.camera.ClassifyParam.input_blob', index=2,
      number=3, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='output_blob', full_name='apollo.perception.camera.ClassifyParam.output_blob', index=3,
      number=4, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='weight_file', full_name='apollo.perception.camera.ClassifyParam.weight_file', index=4,
      number=5, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='proto_file', full_name='apollo.perception.camera.ClassifyParam.proto_file', index=5,
      number=6, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='classify_threshold', full_name='apollo.perception.camera.ClassifyParam.classify_threshold', index=6,
      number=7, type=2, cpp_type=6, label=1,
      has_default_value=False, default_value=float(0),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='classify_resize_width', full_name='apollo.perception.camera.ClassifyParam.classify_resize_width', index=7,
      number=8, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='classify_resize_height', full_name='apollo.perception.camera.ClassifyParam.classify_resize_height', index=8,
      number=9, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='scale', full_name='apollo.perception.camera.ClassifyParam.scale', index=9,
      number=10, type=2, cpp_type=6, label=1,
      has_default_value=False, default_value=float(0),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='mean_b', full_name='apollo.perception.camera.ClassifyParam.mean_b', index=10,
      number=12, type=2, cpp_type=6, label=1,
      has_default_value=True, default_value=float(95),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='mean_g', full_name='apollo.perception.camera.ClassifyParam.mean_g', index=11,
      number=13, type=2, cpp_type=6, label=1,
      has_default_value=True, default_value=float(99),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='mean_r', full_name='apollo.perception.camera.ClassifyParam.mean_r', index=12,
      number=14, type=2, cpp_type=6, label=1,
      has_default_value=True, default_value=float(96),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='is_bgr', full_name='apollo.perception.camera.ClassifyParam.is_bgr', index=13,
      number=15, type=8, cpp_type=7, label=1,
      has_default_value=True, default_value=True,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='traffic_light_recognition_root_dir', full_name='apollo.perception.camera.ClassifyParam.traffic_light_recognition_root_dir', index=14,
      number=16, type=9, cpp_type=9, label=1,
      has_default_value=True, default_value=b"/apollo/modules/perception/production/data/perception/camera/models/traffic_light_recognition".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='gpu_id', full_name='apollo.perception.camera.ClassifyParam.gpu_id', index=15,
      number=17, type=5, cpp_type=1, label=1,
      has_default_value=True, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto2',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=88,
  serialized_end=582,
)


_TRAFFICLIGHTRECOGNITIONCONFIG = _descriptor.Descriptor(
  name='TrafficLightRecognitionConfig',
  full_name='apollo.perception.camera.TrafficLightRecognitionConfig',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='vertical_model', full_name='apollo.perception.camera.TrafficLightRecognitionConfig.vertical_model', index=0,
      number=1, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='quadrate_model', full_name='apollo.perception.camera.TrafficLightRecognitionConfig.quadrate_model', index=1,
      number=2, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='horizontal_model', full_name='apollo.perception.camera.TrafficLightRecognitionConfig.horizontal_model', index=2,
      number=3, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto2',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=585,
  serialized_end=813,
)

_TRAFFICLIGHTRECOGNITIONCONFIG.fields_by_name['vertical_model'].message_type = _CLASSIFYPARAM
_TRAFFICLIGHTRECOGNITIONCONFIG.fields_by_name['quadrate_model'].message_type = _CLASSIFYPARAM
_TRAFFICLIGHTRECOGNITIONCONFIG.fields_by_name['horizontal_model'].message_type = _CLASSIFYPARAM
DESCRIPTOR.message_types_by_name['ClassifyParam'] = _CLASSIFYPARAM
DESCRIPTOR.message_types_by_name['TrafficLightRecognitionConfig'] = _TRAFFICLIGHTRECOGNITIONCONFIG
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

ClassifyParam = _reflection.GeneratedProtocolMessageType('ClassifyParam', (_message.Message,), {
  'DESCRIPTOR' : _CLASSIFYPARAM,
  '__module__' : 'modules.perception.pipeline.proto.stage.recognition_pb2'
  # @@protoc_insertion_point(class_scope:apollo.perception.camera.ClassifyParam)
  })
_sym_db.RegisterMessage(ClassifyParam)

TrafficLightRecognitionConfig = _reflection.GeneratedProtocolMessageType('TrafficLightRecognitionConfig', (_message.Message,), {
  'DESCRIPTOR' : _TRAFFICLIGHTRECOGNITIONCONFIG,
  '__module__' : 'modules.perception.pipeline.proto.stage.recognition_pb2'
  # @@protoc_insertion_point(class_scope:apollo.perception.camera.TrafficLightRecognitionConfig)
  })
_sym_db.RegisterMessage(TrafficLightRecognitionConfig)


# @@protoc_insertion_point(module_scope)
