# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: modules/perception/pipeline/proto/stage/smoke_obstacle_detection_config.proto
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='modules/perception/pipeline/proto/stage/smoke_obstacle_detection_config.proto',
  package='apollo.perception.camera',
  syntax='proto2',
  serialized_options=None,
  create_key=_descriptor._internal_create_key,
  serialized_pb=b'\nMmodules/perception/pipeline/proto/stage/smoke_obstacle_detection_config.proto\x12\x18\x61pollo.perception.camera\"h\n\x1cSmokeObstacleDetectionConfig\x12\x0e\n\x06gpu_id\x18\x01 \x01(\x05\x12\x13\n\x0b\x63\x61mera_name\x18\x02 \x01(\t\x12\x10\n\x08root_dir\x18\x03 \x01(\t\x12\x11\n\tconf_file\x18\x04 \x01(\t'
)




_SMOKEOBSTACLEDETECTIONCONFIG = _descriptor.Descriptor(
  name='SmokeObstacleDetectionConfig',
  full_name='apollo.perception.camera.SmokeObstacleDetectionConfig',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='gpu_id', full_name='apollo.perception.camera.SmokeObstacleDetectionConfig.gpu_id', index=0,
      number=1, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='camera_name', full_name='apollo.perception.camera.SmokeObstacleDetectionConfig.camera_name', index=1,
      number=2, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='root_dir', full_name='apollo.perception.camera.SmokeObstacleDetectionConfig.root_dir', index=2,
      number=3, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='conf_file', full_name='apollo.perception.camera.SmokeObstacleDetectionConfig.conf_file', index=3,
      number=4, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto2',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=107,
  serialized_end=211,
)

DESCRIPTOR.message_types_by_name['SmokeObstacleDetectionConfig'] = _SMOKEOBSTACLEDETECTIONCONFIG
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

SmokeObstacleDetectionConfig = _reflection.GeneratedProtocolMessageType('SmokeObstacleDetectionConfig', (_message.Message,), {
  'DESCRIPTOR' : _SMOKEOBSTACLEDETECTIONCONFIG,
  '__module__' : 'modules.perception.pipeline.proto.stage.smoke_obstacle_detection_config_pb2'
  # @@protoc_insertion_point(class_scope:apollo.perception.camera.SmokeObstacleDetectionConfig)
  })
_sym_db.RegisterMessage(SmokeObstacleDetectionConfig)


# @@protoc_insertion_point(module_scope)
