# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: modules/perception/pipeline/proto/stage/yolo_obstacle_detector_config.proto
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from modules.perception.camera.proto import yolo_pb2 as modules_dot_perception_dot_camera_dot_proto_dot_yolo__pb2


DESCRIPTOR = _descriptor.FileDescriptor(
  name='modules/perception/pipeline/proto/stage/yolo_obstacle_detector_config.proto',
  package='apollo.perception.camera',
  syntax='proto2',
  serialized_options=None,
  create_key=_descriptor._internal_create_key,
  serialized_pb=b'\nKmodules/perception/pipeline/proto/stage/yolo_obstacle_detector_config.proto\x12\x18\x61pollo.perception.camera\x1a*modules/perception/camera/proto/yolo.proto\"\x91\x01\n\x1aYoloObstacleDetectorConfig\x12\x0e\n\x06gpu_id\x18\x01 \x01(\x05\x12\x13\n\x0b\x63\x61mera_name\x18\x02 \x01(\t\x12<\n\nyolo_param\x18\x03 \x01(\x0b\x32(.apollo.perception.camera.yolo.YoloParam\x12\x10\n\x08root_dir\x18\x04 \x01(\t'
  ,
  dependencies=[modules_dot_perception_dot_camera_dot_proto_dot_yolo__pb2.DESCRIPTOR,])




_YOLOOBSTACLEDETECTORCONFIG = _descriptor.Descriptor(
  name='YoloObstacleDetectorConfig',
  full_name='apollo.perception.camera.YoloObstacleDetectorConfig',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='gpu_id', full_name='apollo.perception.camera.YoloObstacleDetectorConfig.gpu_id', index=0,
      number=1, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='camera_name', full_name='apollo.perception.camera.YoloObstacleDetectorConfig.camera_name', index=1,
      number=2, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='yolo_param', full_name='apollo.perception.camera.YoloObstacleDetectorConfig.yolo_param', index=2,
      number=3, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='root_dir', full_name='apollo.perception.camera.YoloObstacleDetectorConfig.root_dir', index=3,
      number=4, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto2',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=150,
  serialized_end=295,
)

_YOLOOBSTACLEDETECTORCONFIG.fields_by_name['yolo_param'].message_type = modules_dot_perception_dot_camera_dot_proto_dot_yolo__pb2._YOLOPARAM
DESCRIPTOR.message_types_by_name['YoloObstacleDetectorConfig'] = _YOLOOBSTACLEDETECTORCONFIG
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

YoloObstacleDetectorConfig = _reflection.GeneratedProtocolMessageType('YoloObstacleDetectorConfig', (_message.Message,), {
  'DESCRIPTOR' : _YOLOOBSTACLEDETECTORCONFIG,
  '__module__' : 'modules.perception.pipeline.proto.stage.yolo_obstacle_detector_config_pb2'
  # @@protoc_insertion_point(class_scope:apollo.perception.camera.YoloObstacleDetectorConfig)
  })
_sym_db.RegisterMessage(YoloObstacleDetectorConfig)


# @@protoc_insertion_point(module_scope)
