# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: modules/drivers/lidar/robosense/proto/lidars_filter_config.proto
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='modules/drivers/lidar/robosense/proto/lidars_filter_config.proto',
  package='apollo.drivers.suteng',
  syntax='proto2',
  serialized_options=None,
  create_key=_descriptor._internal_create_key,
  serialized_pb=b'\n@modules/drivers/lidar/robosense/proto/lidars_filter_config.proto\x12\x15\x61pollo.drivers.suteng\"9\n\x05Lidar\x12\x10\n\x08\x66rame_id\x18\x01 \x02(\t\x12\x0f\n\x07grading\x18\x02 \x02(\x05\x12\r\n\x05point\x18\x03 \x03(\t\";\n\x0cLidarsFilter\x12+\n\x05lidar\x18\x01 \x03(\x0b\x32\x1c.apollo.drivers.suteng.Lidar'
)




_LIDAR = _descriptor.Descriptor(
  name='Lidar',
  full_name='apollo.drivers.suteng.Lidar',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='frame_id', full_name='apollo.drivers.suteng.Lidar.frame_id', index=0,
      number=1, type=9, cpp_type=9, label=2,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='grading', full_name='apollo.drivers.suteng.Lidar.grading', index=1,
      number=2, type=5, cpp_type=1, label=2,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='point', full_name='apollo.drivers.suteng.Lidar.point', index=2,
      number=3, type=9, cpp_type=9, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto2',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=91,
  serialized_end=148,
)


_LIDARSFILTER = _descriptor.Descriptor(
  name='LidarsFilter',
  full_name='apollo.drivers.suteng.LidarsFilter',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='lidar', full_name='apollo.drivers.suteng.LidarsFilter.lidar', index=0,
      number=1, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto2',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=150,
  serialized_end=209,
)

_LIDARSFILTER.fields_by_name['lidar'].message_type = _LIDAR
DESCRIPTOR.message_types_by_name['Lidar'] = _LIDAR
DESCRIPTOR.message_types_by_name['LidarsFilter'] = _LIDARSFILTER
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

Lidar = _reflection.GeneratedProtocolMessageType('Lidar', (_message.Message,), {
  'DESCRIPTOR' : _LIDAR,
  '__module__' : 'modules.drivers.lidar.robosense.proto.lidars_filter_config_pb2'
  # @@protoc_insertion_point(class_scope:apollo.drivers.suteng.Lidar)
  })
_sym_db.RegisterMessage(Lidar)

LidarsFilter = _reflection.GeneratedProtocolMessageType('LidarsFilter', (_message.Message,), {
  'DESCRIPTOR' : _LIDARSFILTER,
  '__module__' : 'modules.drivers.lidar.robosense.proto.lidars_filter_config_pb2'
  # @@protoc_insertion_point(class_scope:apollo.drivers.suteng.LidarsFilter)
  })
_sym_db.RegisterMessage(LidarsFilter)


# @@protoc_insertion_point(module_scope)
