# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: modules/drivers/lidar/robosense/proto/sensor_suteng_conf.proto
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from modules.drivers.lidar.robosense.proto import sensor_suteng_pb2 as modules_dot_drivers_dot_lidar_dot_robosense_dot_proto_dot_sensor__suteng__pb2


DESCRIPTOR = _descriptor.FileDescriptor(
  name='modules/drivers/lidar/robosense/proto/sensor_suteng_conf.proto',
  package='apollo.drivers.suteng',
  syntax='proto2',
  serialized_options=None,
  create_key=_descriptor._internal_create_key,
  serialized_pb=b'\n>modules/drivers/lidar/robosense/proto/sensor_suteng_conf.proto\x12\x15\x61pollo.drivers.suteng\x1a\x39modules/drivers/lidar/robosense/proto/sensor_suteng.proto\"\xdd\x05\n\x0cSutengConfig\x12\x10\n\x08\x66rame_id\x18\x01 \x02(\t\x12+\n\x05model\x18\x02 \x02(\x0e\x32\x1c.apollo.drivers.suteng.Model\x12)\n\x04mode\x18\x03 \x02(\x0e\x32\x1b.apollo.drivers.suteng.Mode\x12\x11\n\tpcap_file\x18\x04 \x01(\t\x12\x10\n\x08npackets\x18\x05 \x01(\x05\x12\x0b\n\x03rpm\x18\x06 \x02(\x02\x12\x1a\n\x0cuse_gps_time\x18\x07 \x02(\x08:\x04true\x12\x14\n\ttime_zone\x18\x08 \x02(\x05:\x01\x38\x12\x18\n\x10\x66iring_data_port\x18\t \x02(\r\x12\x1d\n\x15positioning_data_port\x18\n \x01(\r\x12\x11\n\tmax_range\x18\x0b \x02(\x02\x12\x11\n\tmin_range\x18\x0c \x02(\x02\x12\x11\n\tmax_angle\x18\r \x01(\x02\x12\x11\n\tmin_angle\x18\x0e \x01(\x02\x12\x16\n\x0eview_direction\x18\x0f \x01(\x02\x12\x12\n\nview_width\x18\x10 \x01(\x02\x12\x18\n\x10\x63\x61libration_file\x18\x11 \x02(\t\x12\x18\n\torganized\x18\x12 \x02(\x08:\x05\x66\x61lse\x12\x17\n\x0ftarget_frame_id\x18\x13 \x01(\t\x12\x19\n\nmain_frame\x18\x14 \x01(\x08:\x05\x66\x61lse\x12\x1b\n\x13vehicle_config_path\x18\x15 \x01(\t\x12$\n\x1c\x61\x63\x63urate_vehicle_config_path\x18\x16 \x01(\t\x12!\n\x19lidars_filter_config_path\x18\x17 \x01(\t\x12!\n\x19lidar_extrinsic_file_path\x18\x18 \x01(\t\x12\x14\n\x0cscan_channel\x18\x19 \x02(\t\x12\x12\n\npc_channel\x18\x1a \x02(\t\x12\x16\n\x0e\x66usion_channel\x18\x1b \x01(\t\x12\x1b\n\x13\x63ompensator_channel\x18\x1c \x01(\t'
  ,
  dependencies=[modules_dot_drivers_dot_lidar_dot_robosense_dot_proto_dot_sensor__suteng__pb2.DESCRIPTOR,])




_SUTENGCONFIG = _descriptor.Descriptor(
  name='SutengConfig',
  full_name='apollo.drivers.suteng.SutengConfig',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='frame_id', full_name='apollo.drivers.suteng.SutengConfig.frame_id', index=0,
      number=1, type=9, cpp_type=9, label=2,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='model', full_name='apollo.drivers.suteng.SutengConfig.model', index=1,
      number=2, type=14, cpp_type=8, label=2,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='mode', full_name='apollo.drivers.suteng.SutengConfig.mode', index=2,
      number=3, type=14, cpp_type=8, label=2,
      has_default_value=False, default_value=1,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='pcap_file', full_name='apollo.drivers.suteng.SutengConfig.pcap_file', index=3,
      number=4, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='npackets', full_name='apollo.drivers.suteng.SutengConfig.npackets', index=4,
      number=5, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='rpm', full_name='apollo.drivers.suteng.SutengConfig.rpm', index=5,
      number=6, type=2, cpp_type=6, label=2,
      has_default_value=False, default_value=float(0),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='use_gps_time', full_name='apollo.drivers.suteng.SutengConfig.use_gps_time', index=6,
      number=7, type=8, cpp_type=7, label=2,
      has_default_value=True, default_value=True,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='time_zone', full_name='apollo.drivers.suteng.SutengConfig.time_zone', index=7,
      number=8, type=5, cpp_type=1, label=2,
      has_default_value=True, default_value=8,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='firing_data_port', full_name='apollo.drivers.suteng.SutengConfig.firing_data_port', index=8,
      number=9, type=13, cpp_type=3, label=2,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='positioning_data_port', full_name='apollo.drivers.suteng.SutengConfig.positioning_data_port', index=9,
      number=10, type=13, cpp_type=3, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='max_range', full_name='apollo.drivers.suteng.SutengConfig.max_range', index=10,
      number=11, type=2, cpp_type=6, label=2,
      has_default_value=False, default_value=float(0),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='min_range', full_name='apollo.drivers.suteng.SutengConfig.min_range', index=11,
      number=12, type=2, cpp_type=6, label=2,
      has_default_value=False, default_value=float(0),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='max_angle', full_name='apollo.drivers.suteng.SutengConfig.max_angle', index=12,
      number=13, type=2, cpp_type=6, label=1,
      has_default_value=False, default_value=float(0),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='min_angle', full_name='apollo.drivers.suteng.SutengConfig.min_angle', index=13,
      number=14, type=2, cpp_type=6, label=1,
      has_default_value=False, default_value=float(0),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='view_direction', full_name='apollo.drivers.suteng.SutengConfig.view_direction', index=14,
      number=15, type=2, cpp_type=6, label=1,
      has_default_value=False, default_value=float(0),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='view_width', full_name='apollo.drivers.suteng.SutengConfig.view_width', index=15,
      number=16, type=2, cpp_type=6, label=1,
      has_default_value=False, default_value=float(0),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='calibration_file', full_name='apollo.drivers.suteng.SutengConfig.calibration_file', index=16,
      number=17, type=9, cpp_type=9, label=2,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='organized', full_name='apollo.drivers.suteng.SutengConfig.organized', index=17,
      number=18, type=8, cpp_type=7, label=2,
      has_default_value=True, default_value=False,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='target_frame_id', full_name='apollo.drivers.suteng.SutengConfig.target_frame_id', index=18,
      number=19, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='main_frame', full_name='apollo.drivers.suteng.SutengConfig.main_frame', index=19,
      number=20, type=8, cpp_type=7, label=1,
      has_default_value=True, default_value=False,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='vehicle_config_path', full_name='apollo.drivers.suteng.SutengConfig.vehicle_config_path', index=20,
      number=21, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='accurate_vehicle_config_path', full_name='apollo.drivers.suteng.SutengConfig.accurate_vehicle_config_path', index=21,
      number=22, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='lidars_filter_config_path', full_name='apollo.drivers.suteng.SutengConfig.lidars_filter_config_path', index=22,
      number=23, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='lidar_extrinsic_file_path', full_name='apollo.drivers.suteng.SutengConfig.lidar_extrinsic_file_path', index=23,
      number=24, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='scan_channel', full_name='apollo.drivers.suteng.SutengConfig.scan_channel', index=24,
      number=25, type=9, cpp_type=9, label=2,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='pc_channel', full_name='apollo.drivers.suteng.SutengConfig.pc_channel', index=25,
      number=26, type=9, cpp_type=9, label=2,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='fusion_channel', full_name='apollo.drivers.suteng.SutengConfig.fusion_channel', index=26,
      number=27, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='compensator_channel', full_name='apollo.drivers.suteng.SutengConfig.compensator_channel', index=27,
      number=28, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto2',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=149,
  serialized_end=882,
)

_SUTENGCONFIG.fields_by_name['model'].enum_type = modules_dot_drivers_dot_lidar_dot_robosense_dot_proto_dot_sensor__suteng__pb2._MODEL
_SUTENGCONFIG.fields_by_name['mode'].enum_type = modules_dot_drivers_dot_lidar_dot_robosense_dot_proto_dot_sensor__suteng__pb2._MODE
DESCRIPTOR.message_types_by_name['SutengConfig'] = _SUTENGCONFIG
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

SutengConfig = _reflection.GeneratedProtocolMessageType('SutengConfig', (_message.Message,), {
  'DESCRIPTOR' : _SUTENGCONFIG,
  '__module__' : 'modules.drivers.lidar.robosense.proto.sensor_suteng_conf_pb2'
  # @@protoc_insertion_point(class_scope:apollo.drivers.suteng.SutengConfig)
  })
_sym_db.RegisterMessage(SutengConfig)


# @@protoc_insertion_point(module_scope)
