# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: modules/perception/lidar/lib/scene_manager/roi_service/proto/roi_service.proto
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='modules/perception/lidar/lib/scene_manager/roi_service/proto/roi_service.proto',
  package='apollo.perception.lidar',
  syntax='proto2',
  serialized_options=None,
  create_key=_descriptor._internal_create_key,
  serialized_pb=b'\nNmodules/perception/lidar/lib/scene_manager/roi_service/proto/roi_service.proto\x12\x17\x61pollo.perception.lidar\"?\n\x10ROIServiceConfig\x12\x12\n\x05range\x18\x01 \x01(\x01:\x03\x31\x32\x30\x12\x17\n\tcell_size\x18\x02 \x01(\x01:\x04\x30.25'
)




_ROISERVICECONFIG = _descriptor.Descriptor(
  name='ROIServiceConfig',
  full_name='apollo.perception.lidar.ROIServiceConfig',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='range', full_name='apollo.perception.lidar.ROIServiceConfig.range', index=0,
      number=1, type=1, cpp_type=5, label=1,
      has_default_value=True, default_value=float(120),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='cell_size', full_name='apollo.perception.lidar.ROIServiceConfig.cell_size', index=1,
      number=2, type=1, cpp_type=5, label=1,
      has_default_value=True, default_value=float(0.25),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto2',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=107,
  serialized_end=170,
)

DESCRIPTOR.message_types_by_name['ROIServiceConfig'] = _ROISERVICECONFIG
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

ROIServiceConfig = _reflection.GeneratedProtocolMessageType('ROIServiceConfig', (_message.Message,), {
  'DESCRIPTOR' : _ROISERVICECONFIG,
  '__module__' : 'modules.perception.lidar.lib.scene_manager.roi_service.proto.roi_service_pb2'
  # @@protoc_insertion_point(class_scope:apollo.perception.lidar.ROIServiceConfig)
  })
_sym_db.RegisterMessage(ROIServiceConfig)


# @@protoc_insertion_point(module_scope)
