# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: modules/perception/pipeline/proto/plugin/pointcloud_downsample_config.proto
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='modules/perception/pipeline/proto/plugin/pointcloud_downsample_config.proto',
  package='apollo.perception.lidar',
  syntax='proto2',
  serialized_options=None,
  create_key=_descriptor._internal_create_key,
  serialized_pb=b'\nKmodules/perception/pipeline/proto/plugin/pointcloud_downsample_config.proto\x12\x17\x61pollo.perception.lidar\"\xe1\x01\n\x1aPointcloudDownSampleConfig\x12$\n\x1c\x65nable_downsample_pointcloud\x18\x01 \x01(\x08\x12\x1f\n\x17\x65nable_downsample_beams\x18\x02 \x01(\x08\x12\x13\n\x0bx_min_range\x18\x03 \x01(\x02\x12\x13\n\x0bx_max_range\x18\x04 \x01(\x02\x12\x13\n\x0by_min_range\x18\x05 \x01(\x02\x12\x13\n\x0by_max_range\x18\x06 \x01(\x02\x12\x13\n\x0bz_min_range\x18\x07 \x01(\x02\x12\x13\n\x0bz_max_range\x18\x08 \x01(\x02'
)




_POINTCLOUDDOWNSAMPLECONFIG = _descriptor.Descriptor(
  name='PointcloudDownSampleConfig',
  full_name='apollo.perception.lidar.PointcloudDownSampleConfig',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='enable_downsample_pointcloud', full_name='apollo.perception.lidar.PointcloudDownSampleConfig.enable_downsample_pointcloud', index=0,
      number=1, type=8, cpp_type=7, label=1,
      has_default_value=False, default_value=False,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='enable_downsample_beams', full_name='apollo.perception.lidar.PointcloudDownSampleConfig.enable_downsample_beams', index=1,
      number=2, type=8, cpp_type=7, label=1,
      has_default_value=False, default_value=False,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='x_min_range', full_name='apollo.perception.lidar.PointcloudDownSampleConfig.x_min_range', index=2,
      number=3, type=2, cpp_type=6, label=1,
      has_default_value=False, default_value=float(0),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='x_max_range', full_name='apollo.perception.lidar.PointcloudDownSampleConfig.x_max_range', index=3,
      number=4, type=2, cpp_type=6, label=1,
      has_default_value=False, default_value=float(0),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='y_min_range', full_name='apollo.perception.lidar.PointcloudDownSampleConfig.y_min_range', index=4,
      number=5, type=2, cpp_type=6, label=1,
      has_default_value=False, default_value=float(0),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='y_max_range', full_name='apollo.perception.lidar.PointcloudDownSampleConfig.y_max_range', index=5,
      number=6, type=2, cpp_type=6, label=1,
      has_default_value=False, default_value=float(0),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='z_min_range', full_name='apollo.perception.lidar.PointcloudDownSampleConfig.z_min_range', index=6,
      number=7, type=2, cpp_type=6, label=1,
      has_default_value=False, default_value=float(0),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='z_max_range', full_name='apollo.perception.lidar.PointcloudDownSampleConfig.z_max_range', index=7,
      number=8, type=2, cpp_type=6, label=1,
      has_default_value=False, default_value=float(0),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto2',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=105,
  serialized_end=330,
)

DESCRIPTOR.message_types_by_name['PointcloudDownSampleConfig'] = _POINTCLOUDDOWNSAMPLECONFIG
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

PointcloudDownSampleConfig = _reflection.GeneratedProtocolMessageType('PointcloudDownSampleConfig', (_message.Message,), {
  'DESCRIPTOR' : _POINTCLOUDDOWNSAMPLECONFIG,
  '__module__' : 'modules.perception.pipeline.proto.plugin.pointcloud_downsample_config_pb2'
  # @@protoc_insertion_point(class_scope:apollo.perception.lidar.PointcloudDownSampleConfig)
  })
_sym_db.RegisterMessage(PointcloudDownSampleConfig)


# @@protoc_insertion_point(module_scope)
