# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: modules/perception/pipeline/proto/plugin/resize_and_normalize_config.proto
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='modules/perception/pipeline/proto/plugin/resize_and_normalize_config.proto',
  package='apollo.perception.camera',
  syntax='proto2',
  serialized_options=None,
  create_key=_descriptor._internal_create_key,
  serialized_pb=b'\nJmodules/perception/pipeline/proto/plugin/resize_and_normalize_config.proto\x12\x18\x61pollo.perception.camera\"\xb5\x01\n\x18ResizeAndNormalizeConfig\x12\x15\n\rresized_width\x18\x01 \x01(\x05\x12\x16\n\x0eresized_height\x18\x02 \x01(\x05\x12\r\n\x05scale\x18\x03 \x01(\x02\x12\x0e\n\x06mean_r\x18\x04 \x01(\x02\x12\x0e\n\x06mean_g\x18\x05 \x01(\x02\x12\x0e\n\x06mean_b\x18\x06 \x01(\x02\x12\r\n\x05std_r\x18\x07 \x01(\x02\x12\r\n\x05std_g\x18\x08 \x01(\x02\x12\r\n\x05std_b\x18\t \x01(\x02'
)




_RESIZEANDNORMALIZECONFIG = _descriptor.Descriptor(
  name='ResizeAndNormalizeConfig',
  full_name='apollo.perception.camera.ResizeAndNormalizeConfig',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='resized_width', full_name='apollo.perception.camera.ResizeAndNormalizeConfig.resized_width', index=0,
      number=1, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='resized_height', full_name='apollo.perception.camera.ResizeAndNormalizeConfig.resized_height', index=1,
      number=2, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='scale', full_name='apollo.perception.camera.ResizeAndNormalizeConfig.scale', index=2,
      number=3, type=2, cpp_type=6, label=1,
      has_default_value=False, default_value=float(0),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='mean_r', full_name='apollo.perception.camera.ResizeAndNormalizeConfig.mean_r', index=3,
      number=4, type=2, cpp_type=6, label=1,
      has_default_value=False, default_value=float(0),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='mean_g', full_name='apollo.perception.camera.ResizeAndNormalizeConfig.mean_g', index=4,
      number=5, type=2, cpp_type=6, label=1,
      has_default_value=False, default_value=float(0),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='mean_b', full_name='apollo.perception.camera.ResizeAndNormalizeConfig.mean_b', index=5,
      number=6, type=2, cpp_type=6, label=1,
      has_default_value=False, default_value=float(0),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='std_r', full_name='apollo.perception.camera.ResizeAndNormalizeConfig.std_r', index=6,
      number=7, type=2, cpp_type=6, label=1,
      has_default_value=False, default_value=float(0),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='std_g', full_name='apollo.perception.camera.ResizeAndNormalizeConfig.std_g', index=7,
      number=8, type=2, cpp_type=6, label=1,
      has_default_value=False, default_value=float(0),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='std_b', full_name='apollo.perception.camera.ResizeAndNormalizeConfig.std_b', index=8,
      number=9, type=2, cpp_type=6, label=1,
      has_default_value=False, default_value=float(0),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto2',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=105,
  serialized_end=286,
)

DESCRIPTOR.message_types_by_name['ResizeAndNormalizeConfig'] = _RESIZEANDNORMALIZECONFIG
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

ResizeAndNormalizeConfig = _reflection.GeneratedProtocolMessageType('ResizeAndNormalizeConfig', (_message.Message,), {
  'DESCRIPTOR' : _RESIZEANDNORMALIZECONFIG,
  '__module__' : 'modules.perception.pipeline.proto.plugin.resize_and_normalize_config_pb2'
  # @@protoc_insertion_point(class_scope:apollo.perception.camera.ResizeAndNormalizeConfig)
  })
_sym_db.RegisterMessage(ResizeAndNormalizeConfig)


# @@protoc_insertion_point(module_scope)
