# Currently only configures 1 camera and 1 LiDAR
# To be updated to configure multiple sensors

CAMERA_COUNT = 1
LIDAR_COUNT = 1

CAMERA_LOCATION_X = 0.7
CAMERA_LOCATION_Y = 0.0
CAMERA_LOCATION_Z = 1.7

LIDAR_LOCATION_X = 0.0
LIDAR_LOCATION_Y = 0.0
LIDAR_LOCATION_Z = 1.8

LIDAR_ROTATION_P = 0
LIDAR_ROTATION_Y = 0
LIDAR_ROTATION_R = 0

CAM_IMG_SIZE_X = 1280
CAM_IMG_SIZE_Y = 720
CAM_FOV = 70
CAM_SENSOR_TICK = 0.15

LIDAR_CHANNELS = 16
LIDAR_POINTS_P_SECOND = 1500000
LIDAR_ROTATION_FREQ = 300
LIDAR_LOWER_FOV= -15
LIDAR_UPPER_FOV = 3
LIDAR_RANGE = 50
LIDAR_SENSOR_TICK = 0.1